/////////////////////////////////////////////
/// Create DV index array
/////////////////////////////////////////////
DEFINE_ACTION_MACRO create_dv_index_array BEGIN
    OUTER_SET ind=0
    ACTION_PHP_EACH sfo_joinable_dvs AS dv => discard [[
        array.add[dv_ind]
        [[
            "%dv%" => %ind%
        ]]
        ind++
    ]]
END

/////////////////////////////////////////////
/// Process cre files
/////////////////////////////////////////////

DEFINE_ACTION_MACRO process_cres BEGIN
    //this will process all cre files in the game to extract relevant data from joinable NPCs. Only ever needs to run once as will save to file which can be loaded as required
    IF [FILE_EXISTS "%data_loc%/EJB_script_info.2da"] [[
        PRINT "Processing done already, loading array from file"
        LAF 2da_read STR_VAR file=EJB_scripts.2da path= "%data_loc%" RET_ARRAY script_array=array script_rows=rows END
        LAF 2da_read STR_VAR file=EJB_dvs.2da path= "%data_loc%" RET_ARRAY dv_array=array dv_rows=rows END
    ]] ELSE [[
        PRINT "Processing cre files to extract joinable NPC data. This may take a while..."
        ///Load all relevant CRE files and check if they are joinable NPCs.
        COPY_EXISTING_REGEXP GLOB ~.+\.CRE~ ~override~
            READ_ASCII DEATHVAR "dv" (32) NULL
            TO_LOWER dv
            IF {VARIABLE_IS_SET sfo_joinable_dvs[dv]} 
                    {{
                    //this is a joinable NPC, extract relevant data and save to array
                    READ_STRREF 0x8 name
                    //replace any " " with "@" in the name to avoid issues with 2da writing
                    OUTER_INNER_PATCH_SAVE name ~%name%~ BEGIN
                        REPLACE_TEXTUALLY ~ ~ ~@~
                    END		
                    LOOKUP_IDS_SYMBOL_OF_INT race race (BYTE_AT 0x272)
                    READ_ASCII 0x248 script
                    LOOKUP_IDS_SYMBOL_OF_INT gender gender (BYTE_AT 0x275)
                    weight= calculate_weight{|race="%race%" gender="%gender%"}
                    }}

                    array.add
        2da_write[|file="EJB_scripts.2da" path= "%Wdata_loc%" array="script_array"] 
        2da_write[|file="EJB_dvs.2da" path= "%data_loc%" array="dv_array"] 
        
        PRINT "Data saved to EJB_scripts.2da and EJB_dvs.2da"
    ]]    
    PRINT "Processing complete, arrays loaded and ready for use"
END

 
                
DEFINE_PATCH_FUNCTION calculate_weight
    STR_VAR 
            race= "HUMAN"
            gender= "MALE"
    RET
            weight       
    BEGIN        
        weight_option = check_ini{|ini="weight_option"}
        IF {IS_AN_INT weight__option} {{
            weight = weight_option
        ]] ELSE [[
            IF {!FILE_EXISTS "%MOD_FOLDER%/lib/resource/%weight_option%.2da" && default_weight_option = 0} {{ //if the weight option specified in the ini doesn't exist as a 2da, print a warning and default to 5e weights. Only need to do this check once, hence the default_weight_option variable
                PRINT "Weight Option not found, defaulting to 5e weights"
                SPRINT weight_option "5e"
                default_weight_option = 1
            }}    
            LAF 2da_read STR_VAR file="weight_option.2da" path= "%data_loc%" RET_ARRAY weight_array=array weight_rows=rows END
            check_race = array_contains[|array="weight_rows" key="%race%"]
            IF {!check_race} {{
                PRINT "Race %race% does not have defined weights, defaulting to human"
                SPRINT race "HUMAN"
            }}
            IF {gender = "FEMALE"} {{
                weight = }}
                
    END            


